-- scripts/supabase_analytics.sql
-- Статистика застосунку (Потік 6, byyou) — власна (без Google Analytics/Plausible).
-- Застосувати: Supabase → SQL Editor → New Query → Run. Ідемпотентно (IF NOT EXISTS).
--
-- Що створює:
--   1. analytics_events  — сирі події (перегляд вкладки, встановлення PWA тощо)
--   2. profiles.age      — самозаповнення у профілі (не вираховується)
--   3. RLS                — писати може будь-хто (анонім теж, як реакції/коментарі);
--                           читати сирі рядки — лише is_admin() (уже є, supabase_schema.sql)

-- 1. Сирі події ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id  TEXT NOT NULL,             -- getAnonId() (гість) або auth.uid() (акаунт)
  event_type  TEXT NOT NULL,             -- 'tab_view' | 'pwa_install' | ...
  tab         TEXT,                      -- напр. 'news'|'board'|'chat'|'buses'|'community' (лише для tab_view)
  meta        JSONB,                     -- вільні дані (пристрій, розмір екрана тощо) — розширюваність без нової міграції
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS analytics_events_type_idx       ON analytics_events (event_type);

ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can log an event" ON analytics_events;
CREATE POLICY "Anyone can log an event"
  ON analytics_events FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can read events" ON analytics_events;
CREATE POLICY "Admins can read events"
  ON analytics_events FOR SELECT
  TO authenticated
  USING (is_admin());


-- 2. Вік у профілі (самозаповнення, опційне) -----------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS age INTEGER;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_age_range;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_age_range CHECK (age IS NULL OR (age >= 0 AND age <= 120));

-- Готово. Перевірка після Run:
--   1. Таблиця analytics_events існує, RLS увімкнено, 2 політики видно в Authentication → Policies.
--   2. profiles має колонку age (Table Editor).
