-- scripts/supabase_analytics.sql
-- Статистика застосунку (Потік 6, byyou) — власна (без Google Analytics/Plausible).
-- Застосувати: Supabase → SQL Editor → New Query → Run. Ідемпотентно (IF NOT EXISTS).
--
-- Що створює:
--   1. analytics_events  — сирі події (перегляд вкладки, встановлення PWA тощо)
--   2. RLS                — писати може будь-хто (анонім теж, як реакції/коментарі);
--                           читати сирі рядки — лише is_admin() (уже є, supabase_schema.sql)
--
-- Вік НЕ додаю окремою колонкою — profiles.birth_date (supabase_profiles.sql) вже
-- збирає точну дату народження в анкеті (openProfile/openAccount, account-ui.js).
-- Вік для дашборду рахується з birth_date на льоту (не застаріває щороку, як
-- окреме число). Дублювати в новій колонці — зайве.

-- 1. Сирі події ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id  TEXT NOT NULL,             -- getAnonId() (гість) або auth.uid() (акаунт)
  event_type  TEXT NOT NULL,             -- 'tab_view' | 'pwa_install' | ...
  tab         TEXT,                      -- напр. 'news'|'board'|'chat'|'buses'|'community' (лише для tab_view)
  meta        JSONB,                     -- вільні дані (пристрій, розмір екрана тощо) — розширюваність без нової міграції
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS analytics_events_type_idx       ON analytics_events (event_type);

ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can log an event" ON analytics_events;
CREATE POLICY "Anyone can log an event"
  ON analytics_events FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can read events" ON analytics_events;
CREATE POLICY "Admins can read events"
  ON analytics_events FOR SELECT
  TO authenticated
  USING (is_admin());

-- Готово. Перевірка після Run:
--   1. Таблиця analytics_events існує, RLS увімкнено, 2 політики видно в Authentication → Policies.
