-- ============================================================================
-- CSTL LIFE — Кабінет редактора / Єдина консоль (Фаза 1: фундамент)
-- ============================================================================
-- Запустити у Supabase SQL Editor → New Query → Run.
-- ⚠️ НЕ застосовувати автоматично — це наробки на узгодження (див.
--    docs/EDITOR_CABINET_ARCH.md). Спершу «ок» Роми/Вови.
--
-- Що створює:
--   1. editor_users        — редактори + грануляція дозволів (окремо від admins)
--   2. has_editor_perm()   — security-definer гейт (best practice, оминає RLS)
--   3. cms_articles        — чернетки+готове до публікації (git-схема полів)
--   4. RLS-політики        — справжній захист (не ховання кнопок)
--
-- ПРИНЦИПИ БЕЗПЕКИ (best practices 2026):
--   • RLS на всіх таблицях; політики з роллю `authenticated` (не лише auth.uid()).
--   • RBAC через SECURITY DEFINER функцію (уникаємо рекурсії в політиці).
--   • НЕ чіпаємо is_admin() (на ньому тримається вхід Вови). Супер-адміни
--     автоматично мають усі права редактора.
--   • cms_articles ПУБЛІЧНО НЕ читається — фронт бере git; CI пише service_role.
-- ============================================================================

-- Ідемпотентно (безпечно повторювати; даних ще нема)
DROP TABLE IF EXISTS cms_articles  CASCADE;
DROP TABLE IF EXISTS editor_users  CASCADE;
DROP FUNCTION IF EXISTS has_editor_perm(text) CASCADE;


-- ============================================================================
-- 1. EDITOR_USERS — редактори консолі + їхні дозволи
-- ============================================================================
CREATE TABLE editor_users (
  uid         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email       TEXT UNIQUE,
  name        TEXT,
  can_create  BOOLEAN NOT NULL DEFAULT TRUE,   -- створювати/редагувати чернетки
  can_publish BOOLEAN NOT NULL DEFAULT FALSE,  -- проштовхувати draft → ready (в ефір)
  can_events  BOOLEAN NOT NULL DEFAULT FALSE,  -- керувати подіями «Шо в селі»
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- 2. has_editor_perm() — SECURITY DEFINER (оминає RLS, уникає рекурсії)
-- ============================================================================
-- p: 'create' | 'publish' | 'events'. Супер-адмін (whitelist admins) → усе.
CREATE OR REPLACE FUNCTION has_editor_perm(p TEXT)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    public.is_admin()
    OR COALESCE((
      SELECT CASE
        WHEN p = 'create'  THEN (e.can_create OR e.can_publish)
        WHEN p = 'publish' THEN e.can_publish
        WHEN p = 'events'  THEN e.can_events
        ELSE FALSE
      END
      FROM editor_users e
      WHERE e.uid = auth.uid()
    ), FALSE);
$$;


-- is_team_member(): чи поточний користувач — член команди (адмін АБО редактор).
-- Server-authoritative сторож для сайдбару: гість/чужий → FALSE (не обдуриш з клієнта).
CREATE OR REPLACE FUNCTION is_team_member()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.is_admin()
      OR EXISTS (SELECT 1 FROM editor_users WHERE uid = auth.uid());
$$;


-- ============================================================================
-- 3. CMS_ARTICLES — чернетки + готове до публікації (СХЕМА git-статті!)
-- ============================================================================
-- Поля навмисне повторюють структуру data/articles.json, щоб CI синк-джоб
-- просто нормалізував і пропустив через publish_queue (без мапінгу на фронті).
CREATE TABLE cms_articles (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         TEXT NOT NULL DEFAULT 'news'  CHECK (type IN ('news', 'event')),
  title        TEXT NOT NULL,
  excerpt      TEXT,
  content      TEXT,
  category     TEXT,
  geo          TEXT CHECK (geo IN ('Громада', 'Волинь', 'Україна', 'Світ')),
  image        TEXT,
  image_type   TEXT NOT NULL DEFAULT 'none'  CHECK (image_type IN ('source', 'illustration', 'none')),
  image_credit TEXT,
  source       TEXT NOT NULL DEFAULT 'CSTL LIFE',
  source_url   TEXT,
  exclusive    BOOLEAN NOT NULL DEFAULT TRUE,
  -- draft: пишеться/редагується; ready: Алла натиснула «Публікувати» (чекає синк);
  -- published: CI виклав у git; archived: знято.
  status       TEXT NOT NULL DEFAULT 'draft'
               CHECK (status IN ('draft', 'ready', 'published', 'archived')),
  author_uid   UUID REFERENCES auth.users(id),
  ts           BIGINT,          -- epoch ms (git-сумісно; час публікації)
  git_id       BIGINT,          -- id у articles.json після синку (зворотній зв'язок)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ
);

CREATE INDEX cms_articles_status_idx ON cms_articles (status);
CREATE INDEX cms_articles_author_idx ON cms_articles (author_uid);


-- ============================================================================
-- 4. RLS — справжній захист
-- ============================================================================
ALTER TABLE editor_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_articles ENABLE ROW LEVEL SECURITY;

-- editor_users: керують лише адміни; редактор бачить свій рядок (щоб знати дозволи)
CREATE POLICY editor_users_admin_all ON editor_users
  FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY editor_users_read_self ON editor_users
  FOR SELECT TO authenticated
  USING (uid = auth.uid());

-- cms_articles:
--  • ПУБЛІЧНОГО читання НЕМА (фронт бере git). Редактори бачать усе для консолі.
CREATE POLICY cms_read_editors ON cms_articles
  FOR SELECT TO authenticated
  USING (has_editor_perm('create'));

--  • створювати чернетку: дозвіл create, автор = він сам
CREATE POLICY cms_insert ON cms_articles
  FOR INSERT TO authenticated
  WITH CHECK (has_editor_perm('create') AND author_uid = auth.uid());

--  • редагувати: дозвіл create; АЛЕ проштовхнути status='ready' (в ефір) — лише publish
CREATE POLICY cms_update ON cms_articles
  FOR UPDATE TO authenticated
  USING (has_editor_perm('create'))
  WITH CHECK (
    has_editor_perm('create')
    AND (status <> 'ready' OR has_editor_perm('publish'))
  );

--  • видаляти: свої (або адмін)
CREATE POLICY cms_delete ON cms_articles
  FOR DELETE TO authenticated
  USING (has_editor_perm('create') AND (author_uid = auth.uid() OR public.is_admin()));


-- ============================================================================
-- 5. СИД (заповнити вручну після застосування)
-- ============================================================================
-- Додати Аллу як редактора з правом публікації (uid узяти з auth.users після
-- її першого входу, або завести за email). Приклад:
--   INSERT INTO editor_users (uid, email, name, can_create, can_publish, can_events)
--   VALUES ('<uid_Алли>', 'alla@example.com', 'Алла', TRUE, TRUE, TRUE);
-- Супер-адміни (Вова/Рома) вже мають усе через is_admin() — додавати не треба.
