-- scripts/supabase_ceo_reports.sql
-- ЩОТИЖНЕВІ ЗВІТИ АГЕНТА CEO (21.09.2026). Застосувати: Supabase → SQL Editor → Run.
-- Ідемпотентно.
--
-- 🔴 НАВІЩО ОКРЕМА ТАБЛИЦЯ, А НЕ `analytics_ai_reports`. Там лежить розбір ЦИФР
-- застосунку, тут — стан ПРОЄКТУ проти курсу. Різні джерела, різна частота
-- (кнопка проти неділі) і різні читачі. Зсипати їх в одну таблицю означало б, що
-- «останній звіт» у кабінеті інколи виявляється не тим, за яким прийшли.
--
-- 🔑 Агент пише сюди під `service_role`, тож політики INSERT для людей немає
-- ЗОВСІМ: журнал, у який можна дописати руками, не варто вести взагалі (те саме
-- рішення, що для `analytics_ai_reports`).

CREATE TABLE IF NOT EXISTS ceo_reports (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  model          TEXT,
  prompt_version TEXT,
  report_text    TEXT NOT NULL DEFAULT '',
  -- 🛑 СТАН ПИШЕ САМ АГЕНТ, і це не косметика: два тижні порожньої черги чернеток
  -- сталися рівно тому, що причина мовчання жила лише в лозі GitHub Actions.
  -- «готово» | «пауза» (бюджет) | «збій» | «обірвано» (модель уперлась у стелю
  -- довжини — 🔴 21.09 такий піврозбір ліг сюди зі станом «готово»)
  стан           TEXT NOT NULL DEFAULT 'готово',
  причина        TEXT NOT NULL DEFAULT '',
  cost_usd       NUMERIC(10,4) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ceo_reports_created_idx ON ceo_reports (created_at DESC);

ALTER TABLE ceo_reports ENABLE ROW LEVEL SECURITY;

-- Читають ті, хто має доступ до «Дирекції» в адмінці. Гейт той самий, що в решти
-- адмінських екранів, — щоб право жило в ОДНОМУ місці (RLS), а не в клієнті.
DROP POLICY IF EXISTS "Admins read ceo reports" ON ceo_reports;
CREATE POLICY "Admins read ceo reports"
  ON ceo_reports FOR SELECT
  TO authenticated
  USING (is_admin());

-- Перевірка руками:
--   SELECT created_at, стан, причина, left(report_text, 120)
--     FROM ceo_reports ORDER BY created_at DESC LIMIT 5;
